version: "3"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - $PWD/metrics:/etc/prometheus

  node_exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'