{
 "title": "hw3",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_cpu_seconds_total{mode !='idle'}[5m])) * 100\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transmit bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total[5m])",
     "legendFormat": "{{ device }} {{ instance}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(hits[30s])" }
   ]
  },
  {
   "title": "Receive bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[5m])",
     "legendFormat": "{{device}} {{instance}}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - \nnode_memory_Cached_bytes{} - \nnode_memory_Buffers_bytes{}\n",
     "legendFormat": "Used {{instance}}"
    },
    {}
   ]
  }
 ]
}